version: "3.4"
services:
  web:
    image: konnorscott/appclass:latest
    ports:
      - "5000:5000"
    networks:
      - webnet
  redis:
    image: redis
    networks:
      - webnet
networks:
  webnet: