
version: 2.1

jobs:
  build:
    working_directory: ~/circleci-python
    docker:
      - image: "circleci/python:3.6.4"
    steps:
      - checkout
      - run:
          command: |  # use pipenv to install dependencies
            sudo pip install pipenv
            pipenv install
            pip install requests flask markupsafe
            pip install redis
      - run: python3 appclass.py
  test:
    working_directory: ~/circleci-python
    docker:
      - image: "circleci/python:3.6.4"
    steps:
      - checkout
      - run: python3 testerapp.py

workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build