name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        cd testapp
        docker build -t appclass-tester .

    - name: Build API
      env:
        SLACK_HOOK: ${{ secrets.SLACK_HOOK}}
      run: |
        cd api
        docker build -t konnorscott/appclass .

    - name: Docker compose
      run: |
        docker-compose up -d

    - name: docker ps
      run: |
        docker ps

    - name: test code
      run: |
        cd api
        docker run konnorscott/appclass-tester

    - name: push image
      run: |
        docker login -u ${{ secrets.konnor_u}} -p {{ secrets.konnor_p}}
        docker image tag appclass appclass:latest
        docker image tag appclass  appclass:$$(date +%s)
        docker image push --all-tag appclass
    


