on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
uses: actions/checkout@v2
name: Push the Docker image
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.konnor_u }}
        password: ${{ secrets.konnoe_p}}
        repository: konnorscorr22/lab5
        tags: latest, ${{ github.run_number }}
