name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        docker build -t dockerimage .

    - name: Build API
    env:
      run: |
        cd api
        docker fuild -t dockerimage

    - name: Docker compose
      run: |
        docker-compose up -d

    - name: docker ps
      run: |
        docker ps

    - name: test code
      run: |
        cd api
        docker run dockerimagetestfile

    - name: push image
      run: |
        docker login -u ${{ secrets.konnor_u}} -p {{ secrets.konnor_p}}
        docker image tag 
        docker image tag
        docker image push
    


